### ISSUE TITLE
Referenceing System.Net.Http.Formatting 4.0.0.0

### ISSUE THREAD

**Issue by elestedt** [jlouros/StashApiCSharp#28]
I'm using this in a .NET Core project, which is targeting .NET Framework 4.5.2 and from this library (version 3.0.5) I'm getting errors that it's trying to load the above mentioned dependency - which doesn't exist on the machine.

**Comment by elestedt** [comment]
Just upgraded to 3.0.7 and still getting the same issue:

```
   at Atlassian.Stash.Workers.HttpCommunicationWorker.<PutAsync>d__10`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Atlassian.Stash.Workers.HttpCommunicationWorker.PutAsync[T](String requestUrl, T data)
   at Atlassian.Stash.Api.Projects.<GrantGroup>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Dashboard.Shared.Actions.Services.Bitbucket.CreateProjectAction.<Perform>d__10.MoveNext() in C:\Users\felested\Documents\GitHub\dashboard\src\Dashboard.Shared\Actions\Services\Bitbucket\CreateProjectAction.cs:line 52
```
Fusion log:
```
=== Pre-bind state information ===
LOG: DisplayName = System.Net.Http.Formatting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Users/felested/Documents/GitHub/dashboard/src/Dashboard.Service/bin/Debug/net452/win7-x64/
LOG: Initial PrivatePath = NULL
Calling assembly : Atlassian.Stash, Version=3.0.7.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\felested\Documents\GitHub\dashboard\src\Dashboard.Service\bin\Debug\net452\win7-x64\Dashboard.Service.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Net.Http.Formatting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Attempting download of new URL file:///C:/Users/felested/Documents/GitHub/dashboard/src/Dashboard.Service/bin/Debug/net452/win7-x64/System.Net.Http.Formatting.DLL.
LOG: Attempting download of new URL file:///C:/Users/felested/Documents/GitHub/dashboard/src/Dashboard.Service/bin/Debug/net452/win7-x64/System.Net.Http.Formatting/System.Net.Http.Formatting.DLL.
LOG: Attempting download of new URL file:///C:/Users/felested/Documents/GitHub/dashboard/src/Dashboard.Service/bin/Debug/net452/win7-x64/System.Net.Http.Formatting.EXE.
LOG: Attempting download of new URL file:///C:/Users/felested/Documents/GitHub/dashboard/src/Dashboard.Service/bin/Debug/net452/win7-x64/System.Net.Http.Formatting/System.Net.Http.Formatting.EXE.
```

**Comment by jlouros** [comment]
Not entirely sure what's wrong, but to quickly fix this I'm adding 'Microsoft.AspNet.WebApi.Client' to .Net 4.5 project.
